### PR TITLE
Proofreading _srp (611 words)

### PR DESCRIPTION
**Pull request by nqafield**

### CODE REVIEW

**Comment by yegor256** [comment]
@nqafield thanks!

**Comment by 0crat** [comment]
Oops! There is no order for job `gh:yegor256/blog#206`.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/blog#206` is not in scope.

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this pull request

**Comment by 0crat** [comment]
Job `gh:yegor256/blog#206` is in scope.

**Pull request merged**
