### PR TITLE
Proofreading _recipes

### PR DESCRIPTION
**Pull request by pa9ey**

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this pull request

**Comment by pa9ey** [comment]
@yegor256 I just wanted to point out a couple of things.

In the "politically correct" section I've changed the word "segregate" to "distinguish" because it seemed to make more sense, but I thought maybe you wanted to use "segregate" for the connotations it has. I'll change it back if you want.

The second thing is regarding the "Be Intrinsic" section. This seems not quite right, but I wasn't sure what you were getting at. I presume you mean the manager should "Value Intrinsic Rewards" or "Emphasize Intrinsic Rewards". But the manager himself is not being "intrinsic". What do you think?

**Comment by pa9ey** [comment]
@yegor256 I see now that all the other sections begin with "Be...". Hmm. That makes it trickier.

**Comment by yegor256** [comment]
@pa9ey thanks! I will make final changes now, according to your comments.

**Pull request merged**
