### PR TITLE
Link to translation added

### PR DESCRIPTION
**Pull request by agorlov**
original post:
https://www.yegor256.com/2014/05/05/oop-alternative-to-utility-classes.html

translation:
http://agorlov.ru/oop-alternative-to-utility-classes.html

### CODE REVIEW

**Comment by 0crat** [comment]
@agorlov[/z](https://www.0crat.com/u/agorlov) this pull request is too small, just 1 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @yegor256[/z](https://www.0crat.com/u/yegor256) please review this and merge or reject

**Comment by yegor256** [comment]
@rultor deploy

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by 0crat** [comment]
Job `gh:yegor256/blog#276` is not assigned, can't get performer

**Pull request merged**
