### PR TITLE
Quick proofreading of _new.md

### PR DESCRIPTION
**Pull request by nqafield**

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this pull request

**Comment by 0crat** [comment]
Job `gh:yegor256/blog#214` is now in scope.

**Comment by yegor256** [comment]
@nqafield thanks!

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/blog#214` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job `gh:yegor256/blog#214` is now out of scope.

**Pull request merged**
