### PR TITLE
Update 2015-05-28-one-primary-constructor.md

### PR DESCRIPTION
**Pull request by ashtonhogan**

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this pull request

**Comment by 0crat** [comment]
Job `gh:yegor256/blog#218` is now in scope.

**Comment by yegor256** [comment]
@ashtonhogan thanks!

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/blog#218` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job `gh:yegor256/blog#218` is now out of scope.

**Pull request merged**
