### PR TITLE
Proofreading _sex

### PR DESCRIPTION
**Pull request by pa9ey**

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this pull request

**Comment by pa9ey** [comment]
@yegor256 I have a few questions and comments...

**Comment by pa9ey** [comment]
The reference to "little creatures" is a little confusing perhaps. Are you talking about the children the man will one day have and take care of?

(Actually, that's the only question I think...) :)

**Comment by yegor256** [comment]
@pa9ey thanks!

**Pull request merged**
