### PR TITLE
Proofreading _tasking (2,241 words)

### PR DESCRIPTION
**Pull request by pa9ey**

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this pull request

**Comment by 0crat** [comment]
Job `gh:yegor256/blog#204` is in scope.

**Comment by yegor256** [comment]
@pa9ey thanks!

**Comment by 0crat** [comment]
Oops! There is no order for job `gh:yegor256/blog#204`.

**Comment by 0crat** [comment]
Job `gh:yegor256/blog#204` is now out of scope.

**Pull request merged**
