### PR TITLE
 Proofreading _bugs (540 words)

### PR DESCRIPTION
**Pull request by nqafield**

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job [#259](https://github.com/yegor256/blog/issues/259) is now in scope, role is `REV`

**Comment by nqafield** [comment]
@yegor256 The title is "How to Report a Good Bug". Would "How to Write a Good Bug Report" be better? Or, "The Right Way to Report a Bug"?

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `REV` are banned at this job; I won't be able to assign anyone automatically; consider assigning someone manually or invite more people to the project, as explained in [§51](http://www.zerocracy.com/policy.html#51)

**Comment by yegor256** [comment]
@nqafield you are right, I changed the title

**Comment by 0crat** [comment]
The job [#259](https://github.com/yegor256/blog/issues/259) is now out of scope

**Comment by yegor256** [comment]
@rultor deploy

**Pull request merged**
