### PR TITLE
Proofreading _vesting - first pass (491 words)

### PR DESCRIPTION
**Pull request by nqafield**

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job [#231](https://github.com/yegor256/blog/issues/231) is now in scope, role is `REV`

**Comment by yegor256** [comment]
@nqafield thanks!

**Comment by 0crat** [comment]
The job [#231](https://github.com/yegor256/blog/issues/231) is now out of scope

**Pull request merged**
