### PR TITLE
Update 2024-07-07-checking-object-existence.md

### PR DESCRIPTION
**Pull request by blablatdinov**
Fix python code example.

https://docs.python.org/3/library/pathlib.html
https://peps.python.org/pep-0519/
https://peps.python.org/pep-0428/

### CODE REVIEW

**Comment by blablatdinov** [comment]
@yegor256 take a look please

**Comment by yegor256** [comment]
@blablatdinov to my knowledge, this is "new" Python. Maybe, we should keep two lines for Python: old and new?

**Comment by blablatdinov** [comment]
@yegor256 This class/object available from Python 3.4 . For jui 2024 all supported versions contain `pathlib.Path`.

If you disagree and want to present "old" and "new" methods I change file. Wait you opinion

Diagram of supported python versions: https://devguide.python.org/versions/

**Comment by yegor256** [comment]
@blablatdinov currently, the link provided in the left column leads to a code that is different from what you suggest in the second column. let's make sure they are aligned. and let's show two rows: one for old style one for new. similar to how it's done for JDK

**Comment by blablatdinov** [comment]
@yegor256 Done, take a look

**Comment by yegor256** [comment]
@rultor deploy

**Pull request merged**
