### PR TITLE
Proofreading _parse - first pass (~400 words)

### PR DESCRIPTION
**Pull request by nqafield**

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job [#233](https://github.com/yegor256/blog/issues/233) is now in scope, role is `REV`

**Comment by yegor256** [comment]
@nqafield thanks!

**Comment by 0crat** [comment]
The job [#233](https://github.com/yegor256/blog/issues/233) is now out of scope

**Pull request merged**
