### PR TITLE
 Proofreading _zc (822 words)

### PR DESCRIPTION
**Pull request by nqafield**

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job [#239](https://github.com/yegor256/blog/issues/239) is now in scope, role is `REV`

**Comment by nqafield** [comment]
@yegor256 Just checking... When you said, "How many of them are out there on the markek-the nearest future will show us", where you referring to the XDSD principles, or to the programmers that follow them? If the former, then the PR is okay. Otherwise it will need a slight tweak.

**Comment by yegor256** [comment]
@nqafield I'm referring to programmers. I'm not sure how many of modern programmers will be ready to adopt XDSD principles. Can you please check?

**Comment by nqafield** [comment]
@yegor256 Done now. Sorry about that. :)

**Comment by yegor256** [comment]
@nqafield thanks!

**Comment by 0crat** [comment]
The job [#239](https://github.com/yegor256/blog/issues/239) is now out of scope

**Pull request merged**
