### PR TITLE
Proofreading _arc (1800 words)

### PR DESCRIPTION
**Pull request by nqafield**

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job [#280](https://github.com/yegor256/blog/issues/280) is now in scope, role is `REV`

**Comment by yegor256** [comment]
@nqafield thanks!

**Comment by 0crat** [comment]
Job `gh:yegor256/blog#280` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#280](https://github.com/yegor256/blog/issues/280) is now out of scope

**Comment by yegor256** [comment]
@rultor deploy

**Comment by yegor256** [comment]
@rultor deploy

**Pull request merged**
