### PR TITLE
_bugs edits (22 mins) & _ioc (25 mins)

### PR DESCRIPTION
**Pull request by pa9ey**
See comments on _bugs commit.

(Sorry, I should have done two separate PRs!)

### CODE REVIEW

**Comment by yegor256** [comment]
@pa9ey thanks!

**Comment by pa9ey** [comment]
@yegor256 Can I just double-check you saw the commit comments here: https://github.com/yegor256/blog/pull/157/commits/6a0c5d9f0d56e01cfc0b18ae725ce8e41bb71409

**Comment by yegor256** [comment]
@pa9ey yes, I missed it. Would be better in the future if you post your comments right here, in issue comments.

**Comment by yegor256** [comment]
@pa9ey what do you think would be a better alternative to "discrete"? What I mean there is that neither of that "qualities" is actually measurable, with any reasonable precision.

**Comment by pa9ey** [comment]
@yegor256 You could say they are:
- not [completely] clear
- ambiguous
- open to interpretation

I think I prefer the last one.

**Comment by yegor256** [comment]
@pa9ey I'll go with "ambiguous" :) Thanks

**Pull request merged**
