### PR TITLE
Update agenda.md

### PR DESCRIPTION
**Pull request by ashtonhogan**

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job [#228](https://github.com/yegor256/blog/issues/228) is now in scope, role is `REV`

**Comment by yegor256** [comment]
@ashtonhogan there are some merge conflicts, please fix them. Also, I'm not sure I understand this line, can you please elaborate a bit more...

**Comment by ashtonhogan** [comment]
@yegor256 This could probably be an essay but I'll try and limit my points:

* How does individual autonomy relate to the software industry
* If (insert person here) said it, that makes it legit
* If (insert vendor here) did it, then I agree with it
* If I listen to myself then I don't have to wait for (insert thought leader here) to say it
* Which blogger to listen to vs. Listening to yourself
* We tried something a thought leader said but it failed and now we're blocked
* If I listen to myself, I'll make mistakes and that will waste money (but save my next company money)
* Which technologies do I use? Ones I like or ones that everyone else is using?

**Comment by 0crat** [comment]
Job `gh:yegor256/blog#228` is not assigned, can't get start time

**Comment by 0crat** [comment]
The job [#228](https://github.com/yegor256/blog/issues/228) is now out of scope

**Pull request merged**
