### PR TITLE
Tiny spelling fix.

### PR DESCRIPTION
**Pull request by pa9ey**
TimeLog should be TimedLog.

### CODE REVIEW

**Comment by pa9ey** [comment]
Have I done the right thing there? I wasn't expecting the build to run and fail!

**Comment by yegor256** [comment]
@pa9ey thanks!

**Comment by yegor256** [comment]
@pa9ey everything is correct, thanks!

**Comment by pa9ey** [comment]
@yegor256 Thanks. And you're welcome.

**Pull request merged**
