### PR TITLE
Proofreading _tpl (430 words)

### PR DESCRIPTION
**Pull request by pa9ey**

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this pull request

**Comment by pa9ey** [comment]
@yegor256 "bi-weekly" is an ambiguous word. You may want to change it to "fortnightly" or "twice-weekly".

**Comment by 0crat** [comment]
Job `gh:yegor256/blog#202` is in scope.

**Comment by yegor256** [comment]
@pa9ey thanks! I decided to use "twice-weekly"

**Pull request merged**
