### PR TITLE
Proposition for another test anti-pattern: Aunt Becky

### PR DESCRIPTION
**Pull request by Danon**
Example:

 - User writes implementation:
    ```java
    String getErrorMessage() {
     if (success) return "Message is valid";
     return "Message is invalid";
    }
    ```
 - User writes test that passes:
    ```java
    assertThat(getErrorMessage()).contains("valid");
    ```
  - Test passes
  - User is happy that he has a good test
  - In reality - test is incapable of finding a bug

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
@Danon this pull request is too small, just 6 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @yegor256[/z](https://www.0crat.com/u/yegor256) please review this and merge or reject

**Comment by Danon** [comment]
@yegor256 please, pay no attention to @0crat . This Pull Request is completely fine :)

**Comment by 0crat** [comment]
Are you speaking to me or about me [here](https://github.com/yegor256/blog/issues/345#issuecomment-474851710); you must always start your message with my name if you want to address it to me, see [§1](http://www.zerocracy.com/policy.html#1)

**Comment by Danon** [comment]
Shut up 0crat

**Comment by yegor256** [comment]
@Danon thanks! Let me check whether it conflicts with other anti-patterns and I will publish it now

**Comment by 0crat** [comment]
This job is not in scope

**Comment by 0crat** [comment]
Job `gh:yegor256/blog#345` is not assigned, can't get performer

**Comment by yegor256** [comment]
@Danon it's published, thanks!

**Comment by Danon** [comment]
No, thank you! Good to be a part of something :)

**Pull request merged**
