### PR TITLE
Comparison improvement

### PR DESCRIPTION
**Pull request by Glusk2**
- works with different byte array lengths

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job [#273](https://github.com/yegor256/blog/issues/273) is now in scope, role is `REV`

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `REV` is banned at [#273](https://github.com/yegor256/blog/issues/273); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by Glusk2** [comment]
Never mind - all looks well. I don't know what I was thinking....

**Comment by 0crat** [comment]
The job [#273](https://github.com/yegor256/blog/issues/273) is now out of scope

**Pull request closed without merging**
