### PR TITLE
Proofreading _review (~500 words)

### PR DESCRIPTION
**Pull request by nqafield**

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job [#349](https://github.com/yegor256/blog/issues/349) is now in scope, role is `REV`

**Comment by yegor256** [comment]
@nqafield thanks!

**Comment by 0crat** [comment]
Job `gh:yegor256/blog#349` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#349](https://github.com/yegor256/blog/issues/349) is now out of scope

**Comment by yegor256** [comment]
@rultor deploy

**Pull request merged**
