### PR TITLE
Proofreading _ponzi (587 words)

### PR DESCRIPTION
**Pull request by pa9ey**

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this pull request

**Comment by 0crat** [comment]
Job `gh:yegor256/blog#183` is in scope.

**Comment by pa9ey** [comment]
@yegor256 I changed your initial payment price to $1222, because it made the maths work. Is that okay?

**Comment by yegor256** [comment]
@pa9ey that's fine, thanks!

**Pull request merged**
