### PR TITLE
Update 2018-01-09-micro-budgeting.md

### PR DESCRIPTION
**Pull request by ashtonhogan**

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this pull request

**Comment by 0crat** [comment]
Job `gh:yegor256/blog#220` is now in scope, role is `REV`.

**Comment by nqafield** [comment]
Hi @ashtonhogan. Just out of interest, what are these buffer things? What do they do on the blog?

**Comment by ashtonhogan** [comment]
@nqafield It's a surprise ;)

**Comment by yegor256** [comment]
@ashtonhogan thanks!

**Comment by 0crat** [comment]
Job `gh:yegor256/blog#220` is not assigned, can't get start time

**Comment by 0crat** [comment]
The job [#220](https://github.com/yegor256/blog/issues/220) is now out of scope

**Pull request merged**
