### PR TITLE
Proofreading _factory

### PR DESCRIPTION
**Pull request by pa9ey**

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this pull request

**Comment by 0crat** [comment]
Job `gh:yegor256/blog#199` is in scope.

**Comment by pa9ey** [comment]
Hi @yegor256. I wasn't sure about some of the code. (My Java isn't great.) But around line 170 you have some code that appears to be a private constructor returning something??

**Comment by yegor256** [comment]
@pa9ey thanks!

**Comment by yegor256** [comment]
@pa9ey it's all good, I just checked.

**Pull request merged**
