### PR TITLE
Proofreading _motivation (1237 words)

### PR DESCRIPTION
**Pull request by pa9ey**

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this pull request

**Comment by 0crat** [comment]
Job `gh:yegor256/blog#188` is in scope.

**Comment by pa9ey** [comment]
@yegor256  The first link (to the sarcasm tag) doesn't work. I assume that's just because the post hasn't been deployed yet. But I thought I'd point it out just in case.

**Comment by yegor256** [comment]
@pa9ey thanks!

**Pull request merged**
