### PR TITLE
Update 2015-03-02-team-morale-myths-and-reality.md

### PR DESCRIPTION
**Pull request by ashtonhogan**

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this pull request

**Comment by 0crat** [comment]
Job `gh:yegor256/blog#216` is now in scope.

**Comment by yegor256** [comment]
@ashtonhogan it seems that Twitter doesn't accept long texts via Buffer :( Please, make sure they are shorter than 100 characters.

**Comment by yegor256** [comment]
@ashtonhogan thanks!

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/blog#216` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job `gh:yegor256/blog#216` is now out of scope.

**Pull request merged**
