### PR TITLE
448 fix typo

### LINKED ISSUE #448: Typo in a candidat project name for the Quality Award 2020
There is a typo in the name of a project listed for the Software Quality Award 2020 [here](https://www.yegor256.com/2019/11/03/award-2020.html)

`altiore/altiore.ui` should be `altiore/lorder.ui`

### PR DESCRIPTION
**Pull request by fellahi-ali**
Fix #448

### CODE REVIEW

**Comment by 0crat** [comment]
@fellahi-ali[/z](https://www.0crat.com/u/fellahi-ali) this pull request is too small, just 2 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @yegor256[/z](https://www.0crat.com/u/yegor256) please review this and merge or reject

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@2cbcf229-0ac2-46cd-a04b-76a0f998dfc0, thread: pool-9-thread-1
com.jcabi.github.RtValuePagination$Items[181] java.lang.IllegalStateException: java.io.IOException: failed after 4 attempts
com.jcabi.http.wire.RetryWire[95] java.io.IOException: failed after 4 attempts
```

[0.54.5](https://github.com/zerocracy/farm): Issue: yegor256/blog#449, Action: `created`

**Comment by yegor256** [comment]
@fellahi-ali thanks!

**Comment by 0crat** [comment]
Job `gh:yegor256/blog#449` is not assigned, can't get performer

**Pull request merged**
