### PR TITLE
adding tdd tag

### PR DESCRIPTION
**Pull request by pa9ey**
As per #181

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this pull request

**Comment by 0crat** [comment]
Job `gh:yegor256/blog#182` is in scope.

**Comment by 0crat** [comment]
+15 points just awarded to @pa9ey, total is [+15](http://www.0crat.com/u/pa9ey).

**Comment by yegor256** [comment]
@pa9ey thanks

**Pull request merged**
