### PR TITLE
Added the line at the end of agenda.md about the title of the propose…

### PR DESCRIPTION
**Pull request by VahidKay**
I have been thinking about the roles in a scrum team and how people could work together to have a better product yet I think some things are missing. One of them is still the architect role.

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
@VahidKay this pull request is too small, just 2 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @yegor256[/z](https://www.0crat.com/u/yegor256) please review this and merge or reject

**Comment by yegor256** [comment]
@VahidKay thanks!

**Comment by 0crat** [comment]
Job `gh:yegor256/blog#316` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Pull request merged**
