### PR TITLE
Proofreading _raii (700 words total, 481 non-code words)

### PR DESCRIPTION
**Pull request by pa9ey**

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this pull request

**Comment by pa9ey** [comment]
@yegor256 Regarding the last section of code, you talk about the try/finally block even though there is no finally part. I presume this is because it's not needed, but I wonder if this needs explanation. (Or maybe this is obvious enough to a Java person, unlike myself!) :)

**Comment by yegor256** [comment]
@pa9ey thanks!

**Comment by yegor256** [comment]
@pa9ey thanks for the catch, fixed in 88cafb926c

**Pull request merged**
