### PR TITLE
Update 2017-08-01-how-to-manage-a-manager.md

### PR DESCRIPTION
**Pull request by ashtonhogan**
@yegor256 I noticed that some characters were being cut off because the length was way above 100

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job [#224](https://github.com/yegor256/blog/issues/224) is now in scope, role is `REV`

**Comment by yegor256** [comment]
@ashtonhogan yes, correct, Buffer doesn't understand long tweets :( Please, keep them short.

**Comment by 0crat** [comment]
Job `gh:yegor256/blog#224` is not assigned, can't get start time

**Comment by 0crat** [comment]
The job [#224](https://github.com/yegor256/blog/issues/224) is now out of scope

**Pull request merged**
