### PR TITLE
Proofreading _donate (437 words)

### PR DESCRIPTION
**Pull request by nqafield**

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job [#247](https://github.com/yegor256/blog/issues/247) is now in scope, role is `REV`

**Comment by nqafield** [comment]
@yegor256 The article says that if you click on the button for Cactoos, say, you will see detailed financial reports, but I couldn't find those.

**Comment by yegor256** [comment]
@nqafield thanks! It's not implemented yet, will work tomorrow.

**Comment by 0crat** [comment]
The job [#247](https://github.com/yegor256/blog/issues/247) is now out of scope

**Pull request merged**
