### PR TITLE
 Proofreading _threads (~770 words)

### PR DESCRIPTION
**Pull request by nqafield**
@yegor256 Couple of things...

In a couple of places you're using a `Set` but then you still use `uniq`. I assume this is unnecessary? (Although I've not changed it yet.)

I wasn't sure what you by "white spots" in "But when it comes to concurrency, there are white spots." I've changed it to "blank spots" on the assumption that you mean there's stuff missing. Does that sound right?

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job [#313](https://github.com/yegor256/blog/issues/313) is now in scope, role is `REV`

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#313](https://github.com/yegor256/blog/issues/313); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by yegor256** [comment]
@nqafield yes, that's correct

**Comment by yegor256** [comment]
@nqafield thanks!

**Comment by yegor256** [comment]
@rultor deploy

**Comment by 0crat** [comment]
Job `gh:yegor256/blog#313` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#313](https://github.com/yegor256/blog/issues/313) is now out of scope

**Pull request merged**
