### PR TITLE
Fix a typo in code-ahead.md

### PR DESCRIPTION
**Pull request by 0xfeeddeadbeef**
Forth != 4th

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this pull request

**Comment by 0crat** [comment]
Job `gh:yegor256/blog#203` is in scope.

**Comment by yegor256** [comment]
@0xfeeddeadbeef thanks!

**Comment by 0crat** [comment]
Oops! There is no order for job `gh:yegor256/blog#203`.

**Comment by 0crat** [comment]
Job `gh:yegor256/blog#203` is now out of scope.

**Pull request merged**
