### PR TITLE
Proofreading _static - 360 words

### PR DESCRIPTION
**Pull request by nqafield**

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](http://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job [#222](https://github.com/yegor256/blog/issues/222) is now in scope, role is `REV`

**Comment by yegor256** [comment]
@nqafield thanks!

**Comment by 0crat** [comment]
The job [#222](https://github.com/yegor256/blog/issues/222) is now out of scope

**Comment by 0crat** [comment]
Job `gh:yegor256/blog#222` is not assigned, can't get start time

**Pull request merged**
