### PR TITLE
Update 2018-12-11-unit-testing-anti-patterns.md

### PR DESCRIPTION
**Pull request by Danon**
Anti-pattern "Happy Path" is a bit different than "Liar"/"Success against all odds".

Happy Path is:
 - Testing the expected behaviour, e.g. `DataComparator` asserts `01.02.2019` > `12.04.2018`
 - Not testing unexpected values, e.g. `as.da.2019r.` > `xx.xx.2019`
 - It is possible to make the test fails, e.g. hardcode `return false;`

Liar/Success against all odds is:
 - Performing assertions that can never fail, e.g. `assertTrue(result >= 0);` on `result` that is a square of two numbers
 - It is impossible to make tests fail, because even `return Math.random() > 0.5;` will always pass.

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job [#353](https://github.com/yegor256/blog/issues/353) is now in scope, role is `REV`

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `REV` is banned at [#353](https://github.com/yegor256/blog/issues/353); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `REV` is banned at [#353](https://github.com/yegor256/blog/issues/353); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by yegor256** [comment]
@Danon thanks!

**Comment by 0crat** [comment]
Job `gh:yegor256/blog#353` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#353](https://github.com/yegor256/blog/issues/353) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Pull request merged**
