### PR TITLE
Patch 2

### PR DESCRIPTION
**Pull request by nqafield**
Proofreading _lazy (1060 words)

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job [#256](https://github.com/yegor256/blog/issues/256) is now in scope, role is `REV`

**Comment by yegor256** [comment]
@nqafield thanks!

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `REV` are banned at this job; I won't be able to assign anyone automatically; consider assigning someone manually or invite more people to the project, as explained in [§51](http://www.zerocracy.com/policy.html#51)

**Comment by yegor256** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/blog/issues/256#issuecomment-381932733))

@yegor256 This is what I know about this job, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#256](https://github.com/yegor256/blog/issues/256) is [in scope](http://www.zerocracy.com/policy.html#14) for 4hr
  * The role is `REV`
  * The job is not assigned to anyone
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @nqafield[/z](https://www.0crat.com/u/nqafield): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C3RFVLU72?q=%7Bjob%3A%27gh%3Ayegor256%2Fblog%23256%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/yegor256/blog/issues/256#issuecomment-381938024))

@yegor256 The job [#256](https://github.com/yegor256/blog/issues/256) is now out of scope

**Comment by yegor256** [comment]
@rultor deploy

**Pull request merged**
