### PR TITLE
Propose some architecure-related topics

### PR DESCRIPTION
**Pull request by rozhok**
A couple of interesting topics.

### CODE REVIEW

**Comment by 0crat** [comment]
[@yegor256](http://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job [#221](https://github.com/yegor256/blog/issues/221) is now in scope, role is `REV`

**Comment by yegor256** [comment]
@rozhok thanks

**Comment by 0crat** [comment]
The job [#221](https://github.com/yegor256/blog/issues/221) is now out of scope

**Comment by 0crat** [comment]
Job `gh:yegor256/blog#221` is not assigned, can't get start time

**Pull request merged**
