### PR TITLE
 Proofreading _vars

### PR DESCRIPTION
**Pull request by nqafield**

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job [#282](https://github.com/yegor256/blog/issues/282) is now in scope, role is `REV`

**Comment by nqafield** [comment]
@yegor256 Double-check the first sentence. It wasn't immediately obvious what you were getting at, so check that my change is appropriate.

**Comment by yegor256** [comment]
@nqafield sounds correct, thanks

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `REV` is banned at [#282](https://github.com/yegor256/blog/issues/282); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
Job `gh:yegor256/blog#282` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#282](https://github.com/yegor256/blog/issues/282) is now out of scope

**Comment by yegor256** [comment]
@rultor deploy

**Comment by yegor256** [comment]
@rultor deploy

**Comment by yegor256** [comment]
@rultor deploy

**Pull request merged**
