### PR TITLE
Added more buffers

### PR DESCRIPTION
**Pull request by ashtonhogan**

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this pull request

**Comment by 0crat** [comment]
Job `gh:yegor256/blog#212` is in scope.

**Comment by yegor256** [comment]
@ashtonhogan thanks!

**Comment by 0crat** [comment]
Oops! There is no order for job `gh:yegor256/blog#212`.

**Comment by 0crat** [comment]
Job `gh:yegor256/blog#212` is now out of scope.

**Pull request merged**
