### PR TITLE
Update 2014-05-13-why-null-is-bad.md

### PR DESCRIPTION
**Pull request by ashtonhogan**

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job [#226](https://github.com/yegor256/blog/issues/226) is now in scope, role is `REV`

**Comment by yegor256** [comment]
@ashtonhogan look cool, thanks

**Comment by 0crat** [comment]
Job `gh:yegor256/blog#226` is not assigned, can't get start time

**Comment by 0crat** [comment]
The job [#226](https://github.com/yegor256/blog/issues/226) is now out of scope

**Pull request merged**
