### PR TITLE
 Proofreading _refactoring (~1325 words)

### PR DESCRIPTION
**Pull request by nqafield**

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job [#254](https://github.com/yegor256/blog/issues/254) is now in scope, role is `REV`

**Comment by nqafield** [comment]
@yegor256 Just a heads up: you mention a Groovy script but the link is missing. Also there's no link to the video you mention.

**Comment by yegor256** [comment]
@nqafield I'll fix it all, thanks

**Comment by yegor256** [comment]
@rultor deploy

**Comment by yegor256** [comment]
@rultor deploy

**Pull request merged**
